import type { Metadata } from "next";
// Removed Next font imports to avoid turbopack internal font error
import "./globals.css";

const geistSans = { variable: "" } as any;
const geistMono = { variable: "" } as any;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
